[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://emmyetchnologywebsite.netlify.app"
  NEXT_PUBLIC_SUPABASE_URL = "https://autndhyvgfndaiahonlx.supabase.co"
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_mdVQiRLR6HVJhEcv7KnWOQ_1Yc1fz70"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_mdVQiRLR6HVJhEcv7KnWOQ_1Yc1fz70"
  NEXT_PUBLIC_SPIN_WHEEL_URL = "https://spinwheel.emmytechnology.com/"

[[plugins]]
  package = "@netlify/plugin-nextjs"
